import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { KeyRound, Plus, ShieldCheck, Trash2, Users, X } from 'lucide-react'
import { adminApi, type AdminUser } from '../api/admin'

export default function AdminWorkspace({ accessToken, currentUserId }: { accessToken: string; currentUserId: string }) {
  const client = useQueryClient()
  const [tab, setTab] = useState<'users' | 'teams' | 'roles' | 'audit'>('users')
  const [showCreate, setShowCreate] = useState(false)
  const users = useQuery({ queryKey: ['admin-users'], queryFn: () => adminApi.users(accessToken), enabled: tab === 'users' })
  const teams = useQuery({ queryKey: ['admin-teams'], queryFn: () => adminApi.teams(accessToken), enabled: tab === 'teams' })
  const roles = useQuery({ queryKey: ['admin-roles'], queryFn: () => adminApi.roles(accessToken), enabled: tab === 'roles' })
  const audit = useQuery({ queryKey: ['admin-audit'], queryFn: () => adminApi.auditLogs(accessToken), enabled: tab === 'audit' })
  const remove = useMutation({ mutationFn: (id: string) => adminApi.deleteUser(id, accessToken), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-users'] }) })
  const password = useMutation({ mutationFn: ({ id, value }: { id: string; value: string }) => adminApi.updatePassword(id, value, accessToken) })

  return <main className="admin-page"><div className="admin-heading"><div><p className="eyebrow">ADMINISTRATION</p><h1>Workspace management</h1><p className="muted">Manage users, roles, teams, and access for this workspace.</p></div>{tab === 'users' && <button className="primary-button admin-create" onClick={() => setShowCreate(true)}><Plus size={15} /> Add user</button>}</div><div className="admin-tabs" role="tablist">{(['users', 'teams', 'roles', 'audit'] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item === 'users' ? 'Users' : item === 'teams' ? 'Teams' : item === 'roles' ? 'Roles & permissions' : 'Audit log'}</button>)}</div>{tab === 'users' && <UsersPanel query={users} currentUserId={currentUserId} onDelete={(id) => remove.mutate(id)} onPassword={(id, value) => password.mutate({ id, value })} />} {tab === 'teams' && <TeamsPanel query={teams} accessToken={accessToken} />} {tab === 'roles' && <RolesPanel query={roles} />} {tab === 'audit' && <AuditPanel query={audit} />}{showCreate && <CreateUserModal accessToken={accessToken} onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); void client.invalidateQueries({ queryKey: ['admin-users'] }) }} />}</main>
}

function UsersPanel({ query, currentUserId, onDelete, onPassword }: { query: ReturnType<typeof useQuery<{ items: AdminUser[]; total: number }>>; currentUserId: string; onDelete: (id: string) => void; onPassword: (id: string, value: string) => void }) { if (query.isLoading) return <div className="table-state">Loading workspace users...</div>; if (query.isError) return <div className="table-state error-state">Unable to load workspace users.</div>; return <section className="admin-card"><div className="admin-card-title"><div><h2>User accounts</h2><p>Credentials, status, and workspace roles.</p></div><span>{query.data?.total ?? 0} users</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Security</th><th /></tr></thead><tbody>{query.data?.items.map((user) => <UserRow key={user.id} user={user} isCurrent={user.id === currentUserId} onDelete={onDelete} onPassword={onPassword} />)}</tbody></table></div></section> }

function UserRow({ user, isCurrent, onDelete, onPassword }: { user: AdminUser; isCurrent: boolean; onDelete: (id: string) => void; onPassword: (id: string, value: string) => void }) { const [editing, setEditing] = useState(false); const [value, setValue] = useState(''); return <tr><td><strong>{user.display_name}</strong><small>{user.email}</small></td><td>{user.role ?? 'Assigned role'}</td><td><span className={`admin-status ${user.status === 'ACTIVE' ? 'active' : 'disabled'}`}>{user.status}</span></td><td>{editing ? <span className="password-edit"><input type="password" value={value} onChange={(event) => setValue(event.target.value)} placeholder="12+ characters" /><button onClick={() => { onPassword(user.id, value); setEditing(false); setValue('') }}><KeyRound size={14} /></button></span> : <button className="admin-icon-action" onClick={() => setEditing(true)} title="Change password" aria-label={`Change password for ${user.display_name}`}><KeyRound size={15} /></button>}</td><td>{!isCurrent && <button className="admin-icon-action danger" onClick={() => onDelete(user.id)} title="Disable account" aria-label={`Disable ${user.display_name}`}><Trash2 size={15} /></button>}</td></tr> }

function TeamsPanel({ query, accessToken }: { query: ReturnType<typeof useQuery<{ items: { id: string; name: string; created_at: string }[]; total: number }>>; accessToken: string }) { const [name, setName] = useState(''); const client = useQueryClient(); const create = useMutation({ mutationFn: () => adminApi.createTeam(name, accessToken), onSuccess: () => { setName(''); void client.invalidateQueries({ queryKey: ['admin-teams'] }) } }); return <section className="admin-card"><div className="admin-card-title"><div><h2>Teams</h2><p>Group workspace users for operational access.</p></div></div><form className="admin-inline-form" onSubmit={(event) => { event.preventDefault(); if (name.trim()) create.mutate() }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="New team name" /><button className="primary-button" type="submit" disabled={create.isPending}><Plus size={15} /> Create team</button></form>{query.isLoading ? <div className="table-state">Loading teams...</div> : <div className="admin-list">{query.data?.items.map((team) => <div className="admin-list-row" key={team.id}><Users size={16} /><strong>{team.name}</strong><small>Created {new Date(team.created_at).toLocaleDateString()}</small></div>)}</div>}</section> }

function RolesPanel({ query }: { query: ReturnType<typeof useQuery<{ id: string; name: string; description: string | null; is_system: boolean }[]>> }) { return <section className="admin-card"><div className="admin-card-title"><div><h2>Roles & permissions</h2><p>System roles available to this workspace.</p></div></div><div className="role-grid">{query.data?.map((role) => <article className="role-card" key={role.id}><ShieldCheck size={18} /><strong>{role.name}</strong><span>{role.description ?? 'Workspace access role'}</span><small>{role.is_system ? 'System role' : 'Workspace role'}</small></article>)}</div></section> }

function AuditPanel({ query }: { query: ReturnType<typeof useQuery<{ items: { id: string; action: string; entity_type: string | null; timestamp: string; metadata: Record<string, unknown> }[]; total: number }>> }) { return <section className="admin-card"><div className="admin-card-title"><div><h2>Audit log</h2><p>Recent workspace administration events.</p></div></div><div className="admin-list">{query.data?.items.map((item) => <div className="admin-list-row" key={item.id}><ShieldCheck size={16} /><strong>{item.action.replaceAll('_', ' ')}</strong><small>{item.entity_type ?? 'workspace'} · {new Date(item.timestamp).toLocaleString()}</small></div>)}</div></section> }

function CreateUserModal({ accessToken, onClose, onCreated }: { accessToken: string; onClose: () => void; onCreated: () => void }) { const [form, setForm] = useState({ display_name: '', email: '', password: '', role: 'VIEWER' }); const [error, setError] = useState(''); const create = useMutation({ mutationFn: () => adminApi.createUser(form, accessToken), onSuccess: onCreated, onError: (reason: Error) => setError(reason.message) }); return <div className="admin-modal-backdrop"><section className="admin-modal"><div className="admin-modal-heading"><div><p className="eyebrow">NEW ACCOUNT</p><h2>Add workspace user</h2></div><button className="admin-icon-action" onClick={onClose} aria-label="Close"><X size={17} /></button></div>{error && <div className="auth-error" role="alert">{error}</div>}<form className="custom-auth-form" onSubmit={(event) => { event.preventDefault(); create.mutate() }}><label><span>Name</span><input required value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })} /></label><label><span>Email</span><input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label><span>Temporary password</span><input required minLength={12} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><label><span>Role</span><select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="VIEWER">Viewer</option><option value="TEAM_MANAGER">Team Manager</option><option value="CAMPAIGN_MANAGER">Campaign Manager</option><option value="ADMIN">Admin</option></select></label><button className="primary-button" type="submit" disabled={create.isPending}>{create.isPending ? 'Creating...' : 'Create user'}</button></form></section></div> }