import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, ShieldAlert, ShieldCheck } from 'lucide-react'
import { checkCompliance } from '../api/compliance'

export default function ComplianceCenter({ accessToken }: { accessToken: string }) {
  const [campaignId, setCampaignId] = useState(''); const [recipientId, setRecipientId] = useState('')
  const result = useQuery({ queryKey: ['compliance', campaignId, recipientId], queryFn: () => checkCompliance(campaignId, recipientId, accessToken), enabled: Boolean(campaignId && recipientId) })
  return <main className="compliance-page"><div className="compliance-heading"><div><p className="eyebrow">COMPLIANCE CENTER</p><h1>Before anything leaves.</h1><p className="muted">Review every send decision across authorization, policy, recipient, sender, and domain health.</p></div><span className="compliance-lock"><ShieldCheck size={17} /> SEND-TIME GATE</span></div><section className="compliance-lookup"><label className="form-field"><span>Campaign ID</span><input value={campaignId} onChange={(event) => setCampaignId(event.target.value)} placeholder="Campaign UUID" /></label><label className="form-field"><span>Campaign recipient ID</span><input value={recipientId} onChange={(event) => setRecipientId(event.target.value)} placeholder="Recipient UUID" /></label></section>{result.isLoading && <div className="table-state">Running compliance checks...</div>}{result.isError && <div className="form-error">{result.error.message}</div>}{result.data && <section className={`compliance-result ${result.data.outcome.toLowerCase()}`}><div className="compliance-summary">{result.data.outcome === 'PASS' ? <CheckCircle2 /> : result.data.outcome === 'WARNING' ? <AlertTriangle /> : <ShieldAlert />}<div><p className="eyebrow">DECISION</p><h2>{result.data.outcome}</h2><p>{result.data.outcome === 'PASS' ? 'All required checks passed.' : result.data.outcome === 'WARNING' ? 'Review warnings before proceeding.' : 'This message must not be sent.'}</p></div></div><div className="compliance-checks">{result.data.checks.map((check) => <article className={`compliance-check ${check.outcome.toLowerCase()}`} key={check.name}><span className="check-icon">{check.outcome === 'PASS' ? <CheckCircle2 size={16} /> : check.outcome === 'WARNING' ? <AlertTriangle size={16} /> : <ShieldAlert size={16} />}</span><div><strong>{check.name.replaceAll('_', ' ')}</strong><p>{check.message}</p>{check.remediation && <small>Remediation: {check.remediation}</small>}</div><em>{check.outcome}</em></article>)}</div></section>}</main>
}
