import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Check, Pencil, Plus, Trash2 } from 'lucide-react'
import { contactsApi } from '../api/contacts'

export default function ContactTags({ accessToken }: { accessToken: string }) {
  const client = useQueryClient()
  const [name, setName] = useState('')
  const [editingId, setEditingId] = useState<string | null>(null)
  const [editingName, setEditingName] = useState('')
  const [error, setError] = useState('')
  const tags = useQuery({ queryKey: ['contact-tags'], queryFn: () => contactsApi.canonicalTags(accessToken) })
  const create = useMutation({ mutationFn: () => contactsApi.createCanonicalTag({ name: name.trim() }, accessToken), onSuccess: () => { setName(''); setError(''); void client.invalidateQueries({ queryKey: ['contact-tags'] }) }, onError: (cause) => setError(cause instanceof Error ? cause.message : 'Could not create tag') })
  const rename = useMutation({ mutationFn: () => contactsApi.updateCanonicalTag(editingId!, { name: editingName.trim() }, accessToken), onSuccess: () => { setEditingId(null); setEditingName(''); setError(''); void client.invalidateQueries({ queryKey: ['contact-tags'] }) }, onError: (cause) => setError(cause instanceof Error ? cause.message : 'Could not rename tag') })
  const remove = useMutation({ mutationFn: (id: string) => contactsApi.deleteCanonicalTag(id, accessToken), onSuccess: () => { setError(''); void client.invalidateQueries({ queryKey: ['contact-tags'] }) }, onError: (cause) => setError(cause instanceof Error ? cause.message : 'Could not remove tag') })
  return <main className="contact-form-page"><Link to="/contacts" className="back-link"><ArrowLeft size={16} /> Back to contacts</Link><div className="form-heading"><div><p className="eyebrow">CONTACT MANAGEMENT / SIGNALS</p><h1>Tags</h1><p className="muted">Reusable signals you can apply to any recipient.</p></div></div><section className="management-card"><div className="management-title"><Plus size={16} /><strong>Create a tag</strong></div><form onSubmit={(event) => { event.preventDefault(); if (!name.trim()) { setError('Enter a tag name'); return } void create.mutate() }}><input value={name} onChange={(event) => { setName(event.target.value); setError('') }} placeholder="Tag name" aria-label="Tag name" /><button className="small-button" type="submit" disabled={create.isPending}><Plus size={14} /> {create.isPending ? 'Creating...' : 'Add tag'}</button></form></section>{error && <div className="form-error" role="alert">{error}</div>}<div className="management-title tags-heading"><strong>All tags</strong><span>{tags.data?.length ?? 0}</span></div>{tags.isLoading ? <div className="table-state">Loading tags...</div> : tags.isError ? <div className="table-state error-state">{tags.error.message}</div> : (tags.data ?? []).length === 0 ? <div className="table-state"><strong>No tags yet</strong><span>Create your first tag above.</span></div> : <div className="contact-table-wrap"><table className="contact-table"><thead><tr><th>Tag</th><th>Created</th><th aria-label="Actions" /></tr></thead><tbody>{tags.data?.map((tag) => <tr key={tag.id}>{editingId === tag.id ? <td><form className="tag-edit-form" onSubmit={(event) => { event.preventDefault(); if (editingName.trim()) void rename.mutate() }}><input value={editingName} onChange={(event) => setEditingName(event.target.value)} aria-label="Rename tag" autoFocus /><button className="small-button" type="submit" disabled={rename.isPending}><Check size={14} /> Save</button></form></td> : <td><span className="data-chip">{tag.name}</span></td>}<td className="faded">{new Date(tag.created_at).toLocaleDateString()}</td><td className="row-actions"><button className="icon-button" type="button" aria-label="Rename tag" onClick={() => { setEditingId(tag.id); setEditingName(tag.name) }}><Pencil size={15} /></button><button className="icon-button row-delete" type="button" aria-label="Delete tag" onClick={() => { if (window.confirm(`Delete tag "${tag.name}"?`)) void remove.mutate(tag.id) }}><Trash2 size={15} /></button></td></tr>)}</tbody></table></div>}</main>
}