import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Building2, KeyRound, ShieldCheck, Users } from 'lucide-react'
import { platformAdminApi, type PlatformUser } from '../api/platformAdmin'

export default function PlatformAdmin({ accessToken }: { accessToken: string }) {
  const client = useQueryClient()
  const overview = useQuery({ queryKey: ['platform-overview'], queryFn: () => platformAdminApi.overview(accessToken) })
  const workspaces = useQuery({ queryKey: ['platform-workspaces'], queryFn: () => platformAdminApi.workspaces(accessToken) })
  const users = useQuery({ queryKey: ['platform-users'], queryFn: () => platformAdminApi.users(accessToken) })
  const update = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: { status?: string; role?: string } }) => platformAdminApi.updateUser(id, payload, accessToken), onSuccess: () => client.invalidateQueries({ queryKey: ['platform-users'] }) })
  const password = useMutation({ mutationFn: ({ id, value }: { id: string; value: string }) => platformAdminApi.updatePassword(id, value, accessToken) })

  if (overview.isLoading || users.isLoading || workspaces.isLoading) return <main className="admin-page"><div className="table-state">Loading platform administration...</div></main>
  if (overview.isError || users.isError || workspaces.isError) return <main className="admin-page"><div className="table-state error-state">Unable to load platform administration. This area requires Super Admin access.</div></main>
  return <main className="admin-page"><div className="admin-heading"><div><p className="eyebrow">PLATFORM OWNER</p><h1>Customer workspaces</h1><p className="muted">Global visibility into customer tenants, users, roles, and access.</p></div></div><section className="platform-metrics"><Metric icon={Building2} label="Customer workspaces" value={overview.data?.workspaces ?? 0} /><Metric icon={Users} label="All users" value={overview.data?.users ?? 0} /><Metric icon={ShieldCheck} label="Active users" value={overview.data?.active_users ?? 0} /><Metric icon={KeyRound} label="Disabled users" value={overview.data?.disabled_users ?? 0} /></section><section className="admin-card"><div className="admin-card-title"><div><h2>All customer users</h2><p>Cross-workspace account and access management.</p></div></div><div className="admin-table-wrap"><table className="admin-table platform-user-table"><thead><tr><th>User</th><th>Workspace</th><th>Role</th><th>Status</th><th>Password</th></tr></thead><tbody>{users.data?.items.map((user) => <PlatformUserRow key={user.id} user={user} onUpdate={(payload) => update.mutate({ id: user.id, payload })} onPassword={(value) => password.mutate({ id: user.id, value })} />)}</tbody></table></div></section><section className="admin-card"><div className="admin-card-title"><div><h2>Customer workspaces</h2><p>Tenant status and identifiers.</p></div></div><div className="admin-list">{workspaces.data?.items.map((workspace) => <div className="admin-list-row" key={workspace.id}><Building2 size={16} /><strong>{workspace.name}</strong><small>{workspace.slug} · {workspace.status}</small></div>)}</div></section></main>
}

function Metric({ icon: Icon, label, value }: { icon: typeof Users; label: string; value: number }) { return <article className="platform-metric"><span><Icon size={17} /></span><small>{label}</small><strong>{value.toLocaleString()}</strong></article> }
function PlatformUserRow({ user, onUpdate, onPassword }: { user: PlatformUser; onUpdate: (payload: { status?: string; role?: string }) => void; onPassword: (value: string) => void }) { const [password, setPassword] = useState(''); return <tr><td><strong>{user.display_name}</strong><small>{user.email}</small></td><td><small>{user.tenant_id}</small></td><td><select value={user.role ?? ''} onChange={(event) => onUpdate({ role: event.target.value })}><option value="">Unassigned</option><option value="VIEWER">Viewer</option><option value="ADMIN">Admin</option><option value="SUPER_ADMIN">Super Admin</option></select></td><td><button className="admin-status-button" onClick={() => onUpdate({ status: user.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' })}>{user.status}</button></td><td><span className="password-edit"><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="New password" /><button onClick={() => { if (password.length >= 12) onPassword(password); setPassword('') }} aria-label={`Change password for ${user.display_name}`}><KeyRound size={14} /></button></span></td></tr> }